The run id is z8i38l4i
Epoch: 1 / 30:   0%|                                                         | 1/730 [00:04<50:08,  4.13s/it]
Traceback (most recent call last):
  File "/home/temp/Sami_DLV3+_Brickfield/mainDLV3+.py", line 504, in <module>
    main(args)
  File "/home/temp/Sami_DLV3+_Brickfield/mainDLV3+.py", line 445, in main
    train(args, model, train_loader, test_loader, device, restart = args.restart)
  File "/home/temp/Sami_DLV3+_Brickfield/mainDLV3+.py", line 272, in train
    loss.backward()
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/_tensor.py", line 626, in backward
    torch.autograd.backward(
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/autograd/graph.py", line 823, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 608.00 MiB. GPU 0 has a total capacity of 47.71 GiB of which 436.00 MiB is free. Process 2858169 has 4.20 GiB memory in use. Including non-PyTorch memory, this process has 37.28 GiB memory in use. Of the allocated memory 35.01 GiB is allocated by PyTorch, and 1.66 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
